## Задание 1
1. Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
2. Считать данные с помощью pandas
3. Вывести на экран первые 5 строк
4. Посмотреть на описание признаков и на их содержание


In [2]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('./laptop_price.csv', encoding='latin-1')
df

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69  
1           Intel HD Graphics 6000       macOS  1.34kg       898.94  
2            Intel HD Graphics 620       No OS  1.86kg       575.00  
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45  
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00  
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00  
1300             Intel HD Graphics  Windows 10   1.5kg       229.00  
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00  
1302             Intel HD Graphics  Windows 10   2.2kg       369.00  

[1303 rows x 13 columns]

In [18]:
df.head()

laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3   
1          2   Apple  Macbook Air  Ultrabook    13.3   
2          3      HP       250 G6   Notebook    15.6   
3          4   Apple  MacBook Pro  Ultrabook    15.4   
4          5   Apple  MacBook Pro  Ultrabook    13.3   

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB   
1                            1440x900        Intel Core i5 1.8GHz   8GB   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB   

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg   
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg   
2            256GB SSD         Intel HD Graphics 620  No OS  1.86kg   
3            512GB SSD            AMD Radeon Pro 455  macOS  1.83kg   
4            256GB SSD  Intel Iris Plus Graphics 650  macOS  1.37kg   

   Price_euros  
0      1339.69  
1       898.94  
2       575.00  
3      2537.45  
4      1803.60

In [20]:
df.describe()

laptop_ID       Inches  Price_euros
count  1303.000000  1303.000000  1303.000000
mean    660.155794    15.017191  1123.686992
std     381.172104     1.426304   699.009043
min       1.000000    10.100000   174.000000
25%     331.500000    14.000000   599.000000
50%     659.000000    15.600000   977.000000
75%     990.500000    15.600000  1487.880000
max    1320.000000    18.400000  6099.000000

In [31]:
df.shape

(1303, 13)

## Задание 2
Проведите первичный анализ данных
1. Изучите типы данных
2. Найдите количество пропущенных ячеек в данных
3. Посчитайте основные статистики по всем признакам и поизучайте их

In [28]:
df.dtypes

laptop_ID             int64
Company              object
Product              object
TypeName             object
Inches              float64
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price_euros         float64
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         1303 non-null   int64  
 1   Company           1303 non-null   object 
 2   Product           1303 non-null   object 
 3   TypeName          1303 non-null   object 
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object 
 6   Cpu               1303 non-null   object 
 7   Ram               1303 non-null   object 
 8   Memory            1303 non-null   object 
 9   Gpu               1303 non-null   object 
 10  OpSys             1303 non-null   object 
 11  Weight            1303 non-null   object 
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB


In [30]:
df.describe(include='all')

laptop_ID Company Product  TypeName       Inches   ScreenResolution  \
count   1303.000000    1303    1303      1303  1303.000000               1303   
unique          NaN      19     618         6          NaN                 40   
top             NaN    Dell  XPS 13  Notebook          NaN  Full HD 1920x1080   
freq            NaN     297      30       727          NaN                507   
mean     660.155794     NaN     NaN       NaN    15.017191                NaN   
std      381.172104     NaN     NaN       NaN     1.426304                NaN   
min        1.000000     NaN     NaN       NaN    10.100000                NaN   
25%      331.500000     NaN     NaN       NaN    14.000000                NaN   
50%      659.000000     NaN     NaN       NaN    15.600000                NaN   
75%      990.500000     NaN     NaN       NaN    15.600000                NaN   
max     1320.000000     NaN     NaN       NaN    18.400000                NaN   

                               Cpu   Ram     Memory                    Gpu  \
count                         1303  1303       1303                   1303   
unique                         118     9         39                    110   
top     Intel Core i5 7200U 2.5GHz   8GB  256GB SSD  Intel HD Graphics 620   
freq                           190   619        412                    281   
mean                           NaN   NaN        NaN                    NaN   
std                            NaN   NaN        NaN                    NaN   
min                            NaN   NaN        NaN                    NaN   
25%                            NaN   NaN        NaN                    NaN   
50%                            NaN   NaN        NaN                    NaN   
75%                            NaN   NaN        NaN                    NaN   
max                            NaN   NaN        NaN                    NaN   

             OpSys Weight  Price_euros  
count         1303   1303  1303.000000  
unique           9    179          NaN  
top     Windows 10  2.2kg          NaN  
freq          1072    121          NaN  
mean           NaN    NaN  1123.686992  
std            NaN    NaN   699.009043  
min            NaN    NaN   174.000000  
25%            NaN    NaN   599.000000  
50%            NaN    NaN   977.000000  
75%            NaN    NaN  1487.880000  
max            NaN    NaN  6099.000000

## Задание 3
Ответьте на несколько вопросов
### 3.1 Ноутбуков от какой компании больше всего в наборе данных?
```Смотрим на строку Top - Dell
На самом деле нет...```

In [34]:
df.Company.value_counts()

Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: Company, dtype: int64

In [39]:
df.Company.mode()

0      Dell
1    Lenovo
Name: Company, dtype: object

### 3.2 Какая минимальная и максимальная стоимость у ноутбуков в данных?
```Смотрим на колонку Price_euros. Min = 174, Max = 6099```

In [40]:
min(df.Price_euros), max(df.Price_euros)

(174.0, 6099.0)

### 3.3 Какой самый дорогой ноутбук в данных?
Выведите все характеристики только по этому ноутбуку

Если таких ноутбуков несколько, то выводите их всех

In [32]:
expen = df[df.Price_euros == max(df.Price_euros)]
expen

laptop_ID Company    Product TypeName  Inches  \
196        200   Razer  Blade Pro   Gaming    17.3   

                        ScreenResolution                          Cpu   Ram  \
196  4K Ultra HD / Touchscreen 3840x2160  Intel Core i7 7820HK 2.9GHz  32GB   

      Memory                      Gpu       OpSys  Weight  Price_euros  
196  1TB SSD  Nvidia GeForce GTX 1080  Windows 10  3.49kg       6099.0

## Задание 4
Ответьте на несколько вопросов
### 4.1 Найдите ноутбуки с самой маленькой диагональю в данных?
Выведите только следующие характеристики:
- Компания
- Тип ноутбука
- Диагональ
- Стоимость

Если таких ноутбуков несколько, то выводите их всех

In [48]:
sm_diag = df[df.Inches == min(df.Inches)][['Company','TypeName', 'Inches', 'Price_euros']]
sm_diag

Company            TypeName  Inches  Price_euros
50    Lenovo  2 in 1 Convertible    10.1       319.00
1082  Lenovo  2 in 1 Convertible    10.1       646.27
1114  Lenovo  2 in 1 Convertible    10.1       549.00
1126  Lenovo  2 in 1 Convertible    10.1       479.00

In [88]:
sm_diag2 = df.loc[df.Inches == min(df.Inches),['Company','TypeName', 'Inches', 'Price_euros']]
sm_diag2

Company            TypeName  Inches  Price_euros
50    Lenovo  2 in 1 Convertible    10.1       319.00
1082  Lenovo  2 in 1 Convertible    10.1       646.27
1114  Lenovo  2 in 1 Convertible    10.1       549.00
1126  Lenovo  2 in 1 Convertible    10.1       479.00

### 4.2 Сколько стоит самый дорогой ноутбук у компании HP?

In [51]:
df[df.Company == 'HP'].sort_values('Price_euros')

laptop_ID Company            Product            TypeName  Inches  \
1268       1286      HP   Stream 11-Y000na             Netbook    11.6   
1296       1314      HP   Stream 11-Y000na             Netbook    11.6   
1282       1300      HP   Stream 11-Y000na             Netbook    11.6   
67           69      HP  Stream 14-AX040wm            Notebook    14.0   
1168       1186      HP  Stream 14-AX000nv            Notebook    14.0   
...         ...     ...                ...                 ...     ...   
857         868      HP     EliteBook x360  2 in 1 Convertible    13.3   
1103       1118      HP           ZBook 17         Workstation    17.3   
911         924      HP    Elitebook Folio           Ultrabook    12.5   
1136       1151      HP           ZBook 17         Workstation    17.3   
749         758      HP           Zbook 17         Workstation    17.3   

                         ScreenResolution  \
1268                             1366x768   
1296                             1366x768   
1282                             1366x768   
67                               1366x768   
1168                             1366x768   
...                                   ...   
857       Full HD / Touchscreen 1920x1080   
1103          IPS Panel Full HD 1920x1080   
911   4K Ultra HD / Touchscreen 3840x2160   
1136          IPS Panel Full HD 1920x1080   
749           IPS Panel Full HD 1920x1080   

                                       Cpu   Ram              Memory  \
1268  Intel Celeron Dual Core N3060 1.6GHz   2GB  32GB Flash Storage   
1296  Intel Celeron Dual Core N3060 1.6GHz   2GB  32GB Flash Storage   
1282  Intel Celeron Dual Core N3060 1.6GHz   2GB  32GB Flash Storage   
67    Intel Celeron Dual Core N3060 1.6GHz   4GB            32GB SSD   
1168  Intel Celeron Dual Core N3060 1.6GHz   2GB  32GB Flash Storage   
...                                    ...   ...                 ...   
857             Intel Core i7 7600U 2.8GHz   8GB           256GB SSD   
1103           Intel Core i7 6700HQ 2.6GHz   8GB             1TB HDD   
911               Intel Core M 6Y75 1.2GHz   8GB           240GB SSD   
1136           Intel Core i7 6700HQ 2.6GHz   8GB           256GB SSD   
749          Intel Xeon E3-1535M v5 2.9GHz  16GB           256GB SSD   

                        Gpu       OpSys  Weight  Price_euros  
1268  Intel HD Graphics 400  Windows 10  1.17kg        209.0  
1296  Intel HD Graphics 400  Windows 10  1.17kg        209.0  
1282  Intel HD Graphics 400  Windows 10  1.17kg        209.0  
67    Intel HD Graphics 400  Windows 10  1.44kg        229.0  
1168  Intel HD Graphics 400  Windows 10  1.44kg        249.0  
...                     ...         ...     ...          ...  
857   Intel HD Graphics 620  Windows 10  1.28kg       2559.0  
1103     AMD FirePro W6150M   Windows 7   3.0kg       2899.0  
911   Intel HD Graphics 515  Windows 10  1.09kg       3100.0  
1136   Nvidia Quadro M3000M   Windows 7     3kg       3949.4  
749    Nvidia Quadro M2000M   Windows 7     3kg       4389.0  

[274 rows x 13 columns]

In [64]:
max_price = max(df[df.Company == 'HP'].Price_euros)
exp_hp = df[(df.Company == 'HP') & (df.Price_euros == max_price)]
exp_hp

laptop_ID Company   Product     TypeName  Inches  \
749        758      HP  Zbook 17  Workstation    17.3   

                ScreenResolution                            Cpu   Ram  \
749  IPS Panel Full HD 1920x1080  Intel Xeon E3-1535M v5 2.9GHz  16GB   

        Memory                   Gpu      OpSys Weight  Price_euros  
749  256GB SSD  Nvidia Quadro M2000M  Windows 7    3kg       4389.0

### 4.3 Как много ноутбуков Ultrabook с 8GB RAM?
Найдите сколько таких ультрабуков с 8GB ОЗУ в процентном соотношении относительно всех ультрабуков

In [66]:
df[(df.TypeName == 'Ultrabook') & (df.Ram == '8GB')]

laptop_ID Company               Product   TypeName  Inches  \
0             1   Apple           MacBook Pro  Ultrabook    13.3   
1             2   Apple           Macbook Air  Ultrabook    13.3   
4             5   Apple           MacBook Pro  Ultrabook    13.3   
7             8   Apple           Macbook Air  Ultrabook    13.3   
9            10    Acer               Swift 3  Ultrabook    14.0   
...         ...     ...                   ...        ...     ...   
1236       1254      HP         EliteBook 840  Ultrabook    14.0   
1241       1259    Asus  ZenBook UX310UA-WB71  Ultrabook    13.3   
1261       1279    Asus  ZenBook UX305CA-UBM1  Ultrabook    13.3   
1275       1293    Asus  ZenBook UX305CA-UBM1  Ultrabook    13.3   
1289       1307    Asus  ZenBook UX305CA-UBM1  Ultrabook    13.3   

                        ScreenResolution                         Cpu  Ram  \
0     IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz  8GB   
1                               1440x900        Intel Core i5 1.8GHz  8GB   
4     IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz  8GB   
7                               1440x900        Intel Core i5 1.8GHz  8GB   
9            IPS Panel Full HD 1920x1080  Intel Core i5 8250U 1.6GHz  8GB   
...                                  ...                         ...  ...   
1236                           2560x1440  Intel Core i7 6500U 2.5GHz  8GB   
1241                   Full HD 1920x1080  Intel Core i7 6500U 2.5GHz  8GB   
1261         IPS Panel Full HD 1920x1080    Intel Core M 6Y30 0.9GHz  8GB   
1275         IPS Panel Full HD 1920x1080    Intel Core M 6Y30 0.9GHz  8GB   
1289         IPS Panel Full HD 1920x1080    Intel Core M 6Y30 0.9GHz  8GB   

                   Memory                           Gpu       OpSys  Weight  \
0               128GB SSD  Intel Iris Plus Graphics 640       macOS  1.37kg   
1     128GB Flash Storage        Intel HD Graphics 6000       macOS  1.34kg   
4               256GB SSD  Intel Iris Plus Graphics 650       macOS  1.37kg   
7     256GB Flash Storage        Intel HD Graphics 6000       macOS  1.34kg   
9               256GB SSD        Intel UHD Graphics 620  Windows 10   1.6kg   
...                   ...                           ...         ...     ...   
1236            256GB SSD         Intel HD Graphics 520   Windows 7  1.54kg   
1241            256GB SSD         Intel HD Graphics 520  Windows 10  1.45kg   
1261            512GB SSD         Intel HD Graphics 515  Windows 10   1.2kg   
1275            512GB SSD         Intel HD Graphics 515  Windows 10   1.2kg   
1289            512GB SSD         Intel HD Graphics 515  Windows 10   1.2kg   

      Price_euros  
0         1339.69  
1          898.94  
4         1803.60  
7         1158.70  
9          770.00  
...           ...  
1236      2198.19  
1241      1280.00  
1261       729.00  
1275       729.00  
1289       729.00  

[140 rows x 13 columns]

In [99]:
ultra = df[df.TypeName == 'Ultrabook']
ultra.Ram.value_counts(normalize=True)

8GB     0.714286
16GB    0.183673
4GB     0.071429
12GB    0.015306
24GB    0.005102
32GB    0.005102
6GB     0.005102
Name: Ram, dtype: float64

## Задание 5
### 5.1 Выберите ноутбук клиенту
Клиент хочет подобрать ноутбук с 8GB или 16GB ОЗУ на Windows 10 в стоимости до 500 евро, сколько у него вариантов?


In [67]:
sample1 = df[((df.Ram == '8GB') | (df.Ram == '16GB')) & (df.OpSys == 'Windows 10') & (df.Price_euros <= 500)]
sample1

laptop_ID Company                                   Product  TypeName  \
74           76    Acer                             Aspire E5-475  Notebook   
175         179    Dell                             Inspiron 3567  Notebook   
256         261      HP        15-BW094nd (A6-9220/8GB/128GB/W10)  Notebook   
292         297      HP         17-BS037cl (i3-6006U/8GB/1TB/W10)  Notebook   
313         318    Acer  ES1-523-84K7 (A8-7410/8GB/256GB/FHD/W10)  Notebook   
365         371      HP            15-AY023na (N3710/8GB/2TB/W10)  Notebook   
571         578      HP            14-am079na (N3710/8GB/2TB/W10)  Notebook   
595         602  Lenovo                         IdeaPad 110-15ISK  Notebook   
634         642    Asus         X541NA-GO414T (N3350/8GB/1TB/W10)  Notebook   
702         710  Lenovo                         IdeaPad 320-15ABR  Notebook   
1057       1071    Acer                            Aspire ES1-523  Notebook   
1163       1181  Lenovo                         IdeaPad 310-15ISK  Notebook   
1232       1250    Dell                             Inspiron 3567  Notebook   

      Inches      ScreenResolution                                   Cpu  Ram  \
74      14.0              1366x768              Intel Core i3 6006U 2GHz  8GB   
175     15.6              1366x768            Intel Core i3 7100U 2.4GHz  8GB   
256     15.6              1366x768          AMD A6-Series A6-9220 2.5GHz  8GB   
292     17.3              1600x900              Intel Core i3 6006U 2GHz  8GB   
313     15.6     Full HD 1920x1080             AMD A8-Series 7410 2.2GHz  8GB   
365     15.6              1366x768  Intel Pentium Quad Core N3710 1.6GHz  8GB   
571     14.0              1366x768  Intel Pentium Quad Core N3710 1.6GHz  8GB   
595     15.6              1366x768            Intel Core i3 6100U 2.3GHz  8GB   
634     15.6              1366x768  Intel Celeron Dual Core N3350 1.1GHz  8GB   
702     15.6              1366x768           AMD A12-Series 9720P 3.6GHz  8GB   
1057    15.6              1366x768             AMD A8-Series 7410 2.2GHz  8GB   
1163    15.6              1366x768            Intel Core i3 6006U 2.0GHz  8GB   
1232    15.6  Touchscreen 1366x768            Intel Core i3 7100U 2.4GHz  8GB   

         Memory                     Gpu       OpSys  Weight  Price_euros  
74      1TB HDD   Intel HD Graphics 520  Windows 10   2.1kg       389.00  
175     1TB HDD   Intel HD Graphics 620  Windows 10   2.3kg       459.00  
256   128GB SSD  AMD Radeon R4 Graphics  Windows 10  1.91kg       445.90  
292     1TB HDD   Intel HD Graphics 520  Windows 10  2.54kg       489.00  
313   256GB SSD           AMD Radeon R5  Windows 10  2.23kg       469.00  
365     2TB HDD   Intel HD Graphics 405  Windows 10  2.04kg       389.00  
571     2TB HDD   Intel HD Graphics 405  Windows 10  1.94kg       389.00  
595     1TB HDD   Intel HD Graphics 520  Windows 10  2.29kg       459.00  
634     1TB HDD   Intel HD Graphics 500  Windows 10     2kg       399.00  
702     1TB HDD           AMD Radeon R7  Windows 10   2.2kg       429.00  
1057    1TB HDD           AMD Radeon R5  Windows 10   2.4kg       449.00  
1163    1TB HDD   Intel HD Graphics 520  Windows 10   2.2kg       459.00  
1232    1TB HDD   Intel HD Graphics 620  Windows 10   2.3kg       469.01

In [69]:
sample1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13 entries, 74 to 1232
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         13 non-null     int64  
 1   Company           13 non-null     object 
 2   Product           13 non-null     object 
 3   TypeName          13 non-null     object 
 4   Inches            13 non-null     float64
 5   ScreenResolution  13 non-null     object 
 6   Cpu               13 non-null     object 
 7   Ram               13 non-null     object 
 8   Memory            13 non-null     object 
 9   Gpu               13 non-null     object 
 10  OpSys             13 non-null     object 
 11  Weight            13 non-null     object 
 12  Price_euros       13 non-null     float64
dtypes: float64(2), int64(1), object(10)
memory usage: 1.4+ KB


In [101]:
sample1.shape[0]

13

```**Ответ:** 13```

### 5.2 Выберите ноутбук клиенту
Клиент хочет подобрать ноутбук от MSI, с видеокартой Nvidia GeForce GTX 1050 Ti и главное не с диагональю 15.6. В какой ценовой категории вышли подобные ноутбуки?


In [75]:
sample2 = df[(df.Company == 'MSI') & (df.Gpu == 'Nvidia GeForce GTX 1050 Ti') & ~(df.Inches == 15.6)]
sample2.sort_values('Price_euros')

laptop_ID Company        Product TypeName  Inches   ScreenResolution  \
330         336     MSI     GL72M 7REX   Gaming    17.3  Full HD 1920x1080   
724         732     MSI     GL72M 7REX   Gaming    17.3  Full HD 1920x1080   
393         400     MSI  Leopard GP72M   Gaming    17.3  Full HD 1920x1080   
1156       1174     MSI     GP72M 7REX   Gaming    17.3  Full HD 1920x1080   
917         931     MSI     GE72VR 6RF   Gaming    17.3  Full HD 1920x1080   

                              Cpu   Ram                Memory  \
330   Intel Core i7 7700HQ 2.8GHz   8GB  256GB SSD +  1TB HDD   
724   Intel Core i7 7700HQ 2.8GHz   8GB  128GB SSD +  1TB HDD   
393   Intel Core i7 7700HQ 2.8GHz   8GB             256GB SSD   
1156  Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD   
917   Intel Core i7 7700HQ 2.8GHz  16GB  256GB SSD +  1TB HDD   

                             Gpu       OpSys Weight  Price_euros  
330   Nvidia GeForce GTX 1050 Ti  Windows 10  2.7kg      1199.00  
724   Nvidia GeForce GTX 1050 Ti  Windows 10  2.7kg      1348.48  
393   Nvidia GeForce GTX 1050 Ti  Windows 10  2.7kg      1349.00  
1156  Nvidia GeForce GTX 1050 Ti  Windows 10  2.7kg      1492.80  
917   Nvidia GeForce GTX 1050 Ti  Windows 10  2.7kg      1599.00

In [76]:
min(sample2.Price_euros), max(sample2.Price_euros)

(1199.0, 1599.0)

### 5.3 Что дешевле?
В среднем дешевле ноутбуки с CPU Intel Core i7 7700HQ 2.8GHz или с Intel Core i7 7600U 2.8GHz?

In [79]:
sample3a = df[df.Cpu == 'Intel Core i7 7700HQ 2.8GHz']['Price_euros']
sample3b = df[df.Cpu == 'Intel Core i7 7600U 2.8GHz']['Price_euros']

In [86]:
sample3a.mean(), sample3b.mean()

(1760.4084246575337, 1915.710769230769)

## Задание 6
Найдите самый легкий ноутбук

Но обратите внимание на тип и представление данных в признаке Weight, если что, замените в строке 'kg' на пустую строку через метод .str.replace()

In [89]:
df

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69  
1           Intel HD Graphics 6000       macOS  1.34kg       898.94  
2            Intel HD Graphics 620       No OS  1.86kg       575.00  
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45  
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00  
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00  
1300             Intel HD Graphics  Windows 10   1.5kg       229.00  
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00  
1302             Intel HD Graphics  Windows 10   2.2kg       369.00  

[1303 rows x 13 columns]

In [92]:
df[df.Weight.str.contains('kg')]

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69  
1           Intel HD Graphics 6000       macOS  1.34kg       898.94  
2            Intel HD Graphics 620       No OS  1.86kg       575.00  
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45  
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00  
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00  
1300             Intel HD Graphics  Windows 10   1.5kg       229.00  
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00  
1302             Intel HD Graphics  Windows 10   2.2kg       369.00  

[1303 rows x 13 columns]

In [109]:
df_w = df
df_w.Weight = df_w.Weight.str.replace('kg', '')

df_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         1303 non-null   int64  
 1   Company           1303 non-null   object 
 2   Product           1303 non-null   object 
 3   TypeName          1303 non-null   object 
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object 
 6   Cpu               1303 non-null   object 
 7   Ram               1303 non-null   object 
 8   Memory            1303 non-null   object 
 9   Gpu               1303 non-null   object 
 10  OpSys             1303 non-null   object 
 11  Weight            1303 non-null   object 
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB


In [111]:
df_w

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS   1.37      1339.69  
1           Intel HD Graphics 6000       macOS   1.34       898.94  
2            Intel HD Graphics 620       No OS   1.86       575.00  
3               AMD Radeon Pro 455       macOS   1.83      2537.45  
4     Intel Iris Plus Graphics 650       macOS   1.37      1803.60  
...                            ...         ...    ...          ...  
1298         Intel HD Graphics 520  Windows 10    1.8       638.00  
1299         Intel HD Graphics 520  Windows 10    1.3      1499.00  
1300             Intel HD Graphics  Windows 10    1.5       229.00  
1301            AMD Radeon R5 M330  Windows 10   2.19       764.00  
1302             Intel HD Graphics  Windows 10    2.2       369.00  

[1303 rows x 13 columns]

In [112]:
df_w.Weight = df_w.Weight.astype('float64')
df_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         1303 non-null   int64  
 1   Company           1303 non-null   object 
 2   Product           1303 non-null   object 
 3   TypeName          1303 non-null   object 
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object 
 6   Cpu               1303 non-null   object 
 7   Ram               1303 non-null   object 
 8   Memory            1303 non-null   object 
 9   Gpu               1303 non-null   object 
 10  OpSys             1303 non-null   object 
 11  Weight            1303 non-null   float64
 12  Price_euros       1303 non-null   float64
dtypes: float64(3), int64(1), object(9)
memory usage: 132.5+ KB


In [113]:
df_w[df_w.Weight == min(df_w.Weight)]

laptop_ID Company    Product            TypeName  Inches  \
50           51  Lenovo  Yoga Book  2 in 1 Convertible    10.1   
1082       1097  Lenovo  Yoga Book  2 in 1 Convertible    10.1   
1114       1129  Lenovo  Yoga Book  2 in 1 Convertible    10.1   
1126       1141  Lenovo  Yoga Book  2 in 1 Convertible    10.1   

                     ScreenResolution                          Cpu  Ram  \
50    IPS Panel Touchscreen 1920x1200  Intel Atom x5-Z8550 1.44GHz  4GB   
1082  IPS Panel Touchscreen 1920x1200  Intel Atom x5-Z8550 1.44GHz  4GB   
1114  IPS Panel Touchscreen 1920x1200  Intel Atom x5-Z8550 1.44GHz  4GB   
1126  IPS Panel Touchscreen 1920x1200  Intel Atom x5-Z8550 1.44GHz  4GB   

                  Memory                    Gpu       OpSys  Weight  \
50    64GB Flash Storage  Intel HD Graphics 400     Android    0.69   
1082  64GB Flash Storage  Intel HD Graphics 400  Windows 10    0.69   
1114  64GB Flash Storage  Intel HD Graphics 400     Android    0.69   
1126  64GB Flash Storage  Intel HD Graphics 400  Windows 10    0.69   

      Price_euros  
50         319.00  
1082       646.27  
1114       549.00  
1126       479.00